- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.14.0
  hooks:
    - id: ruff

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black
      language_version: python3.13

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      language_version: python3.13
