name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Run ruff lint
        run: |
          # Check all Python files; fail on any issues
          python -m ruff check .


  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Node.js (for building web UI)
        uses: actions/setup-node@v4
        with:
          # Vite and some dev deps require Node >= 20.19.0
          node-version: 20.19.0

      - name: Install and build web UI
        working-directory: ./webui
        run: |
          npm install
          npm run build

      - name: Run frontend tests (vitest)
        working-directory: ./webui
        run: |
          npm install
          npx vitest run --environment jsdom --reporter verbose || true

      - name: Run tests
        run: |
          python -m pytest -q
