name: Generate OpenAPI JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate OpenAPI JSON
        run: |
          python tools/generate_openapi.py

      - name: Upload openapi.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-json
          path: openapi.json

      - name: Commit openapi.json back to repo (optional)
        if: github.actor != 'github-actions[bot]'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add openapi.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(ci): update generated openapi.json [skip ci]" || true
            git push origin HEAD:main || true
          fi
