name: Pin dependencies

on:
  push:
    paths:
      - 'requirements.txt'
  pull_request:
    paths:
      - 'requirements.txt'

jobs:
  pin-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install pip-tools
        run: python -m pip install --upgrade pip pip-tools

      - name: Generate requirements.lock
        run: |
          if [ -f requirements.txt ]; then
            pip-compile --output-file=requirements.lock requirements.txt
          else
            echo "requirements.txt not found"; exit 0
          fi

      - name: Install dependencies for tests
        run: |
          if [ -f requirements.lock ]; then
            pip install -r requirements.lock
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements file found; skipping dependency install"
          fi

      - name: Run tests
        run: |
          python -m pytest -q

      - name: Create pull request with updated requirements.lock
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pinned deps (requirements.lock)"
          commit-author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "chore: update pinned deps (requirements.lock)"
          body: |
            This PR was auto-generated by the `Pin dependencies` workflow.
            It updates `requirements.lock` from `requirements.txt` using `pip-compile`.
          base: main
          branch: "pin-deps/update-requirements-lock-${{ github.run_id }}"
          labels: |
            dependencies
            automated
